apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
  labels:
    app: iot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
      - name: iot-app
        image: wil42/playground:v1  # Will be updated by ArgoCD
        ports:
        - containerPort: 8888
        env:
        - name: APP_VERSION
          value: "v1"
