apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-app-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: playground.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: iot-app-service
            port:
              number: 8888
